name: Secret Scan

on:
  pull_request:
    branches: [main]

jobs:
  secret-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate secret detection
        run: |
          echo "AWS Secret Found!"
          exit 1
