name: Secure Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Pipeline test
        run: echo "Security pipeline is running"
